### ISSUE TITLE
Passing functions instead of their names

### ISSUE THREAD

**Issue by omidkrad** [brownieboy/es6bindall#1]
Hi, I'm trying to modify your `bindAll` function to get method refs for parameters instead of method names, so instead of passing strings I can pass functions directly, for example `bindAll(this, this.onValidate)`. The benefit with passing functions directly is that unlike magic strings, you can get compiler verification on them (I'm using TypeScript), so that if a method name is changed, you get a compiler error.

The following, however, doesn't work:

``` js
bindAll(context, ...methods) {
    methods.map(method => {
        try {
            method = method.bind(context);
            //context[methodName] = context[methodName].bind(context);
        } catch (e) {
            var cName = context.name ? (", " + context.name) : "";
            throw new Error("Cannot bind method '" + methodName +
                "' to the supplied context" + cName + ".");
        }
        return null;
    });
}
```

Do you know if we can fix it or are we hitting a JS limitation here?

Thanks!

**Comment by brownieboy** [comment]
@omidkrad,

What parameters are you passing to bindAll?

**Comment by brownieboy** [comment]
I think you need square brackets around the spread operator, so`[...methods]` rather than `...methods`.

Even then, I could find no way to bind to an actual function/method rather than its name.  I tried getting the function's name using the `function.name` ES6 syntax, but it didn't work for me.

**Comment by omidkrad** [comment]
Hi, `...methods` gets the rest of the parameters in an array. if it's not provided then `methods` will be empty array (see [here](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=var%20helper%20%3D%20%7B%0D%0A%20%20bindAll%28context%2C%20...methodNames%29%20%7B%0D%0A%09%20%20console.log%28methodNames%29%3B%0D%0A%20%20%7D%20%20%0D%0A%7D%0D%0A)). Following works for me just fine with strings:

``` js
bindAll(context, ...methodNames) {
    methodNames.map(methodName => {
        context[methodName] = context[methodName].bind(context);
    }
}
```

OK, if don't know a way to pass actual functions I just go ahead and close this issue. If I find anything I will update here. Thank you.

**Comment by brownieboy** [comment]
What I meant (but didn't actually say!) was that when I passed an array of strings to just `...methodNames`, it was interpreted as a single, comma-separated string in the loop.  Changing it to `[...methodNames]` changed it to an array.
